version: '2.1'
services:
  youtrain-db:
    build: src/test/resources/mariadb
    logging:
      driver: syslog
      options:
        syslog-address: tcp://$HOST_IP:5000
        tag: db-tag
    ports:
      - 3306:3306

  youtrain-db-adminer:
    image: adminer:4.7
    links:
      - youtrain-db
    ports:
      - 8081:8080

  youtrain-server:
    image: registry.gitlab.com/tarent/youtrain-server:${BUILD_NUMBER:-latest}
    environment:
      - spring.datasource.url=jdbc:mysql://youtrain-db:3306/ta_youtrain
    links:
      - youtrain-db
    logging:
      driver: syslog
      options:
        syslog-address: tcp://$HOST_IP:5000
        tag: backend-tag
    depends_on:
      youtrain-db:
        condition: service_healthy  # no longer supported in dcoker-compose file version 3
                                    # look into https://github.com/jwilder/dockerize instead
                                    # or build retry into your service (probably preferable)
    ports:
      - 8080:8080
